"""empty message

Revision ID: 26413106c393
Revises: 366cd38f73b1
Create Date: 2022-09-26 18:29:15.598241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26413106c393'
down_revision = '366cd38f73b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'image_url')
    # ### end Alembic commands ###
